###get list from sercer

GET http://localhost:8000/api/v1/task

###post listfrom server
POST http://localhost:8000/api/v1/task
# header of the request
Content-Type: application/json


# bpdy pf the request, there shoukd be gap between header and body part
{
"task":"game  ",
"hr": 40,
"type":"entry"
}
###update data
PATCH  http://localhost:8000/api/v1/task
# header of the request
Content-Type: application/json


# bpdy pf the request, there shoukd be gap between header and body part
{
  "id":"",
  "type":"bad"
} 

###delete data
DELETE http://localhost:8000/api/v1/task
# header of the request
Content-Type: application/json

# bpdy pf the request, there shoukd be gap between header and body part
{
  "id":"nhs2I3"
  
}

